# Generated by Django 6.1 on 2026-08-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='city',
            field=models.CharField(null=True),
        ),
    ]
