# Generated by Django 4.2.8 on 2026-09-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produts',
        ),
    ]
