# Generated by Django 4.2.8 on 2026-08-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_desc',
        ),
    ]
