# Generated by Django 6.1 on 2026-09-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
